"""Ручной маппинг карточка -> теги эффектов.

Источник правды. Изменения здесь -> build_effect_tags.py -> docs/effect_tags.json.
"""
from __future__ import annotations

TAG_LABELS: dict[str, str] = {
    "sleep":       "Сон",
    "stress":      "Стресс / тревога",
    "mood":        "Настроение",
    "brain":       "Мозг / память",
    "energy":      "Энергия / бодрость",
    "immunity":    "Иммунитет",
    "heart":       "Сердце / сосуды",
    "blood":       "Кровь",
    "muscle":      "Мышцы / спорт",
    "joints":      "Суставы",
    "bones":       "Кости",
    "skin":        "Кожа / волосы",
    "metabolism":  "Метаболизм / вес",
    "gut":         "ЖКТ / кишечник",
    "hormones":    "Гормоны",
    "vision":      "Зрение",
    "urinary":     "Мочевыводящие",
    "liver":       "Печень",
}

TAGS: dict[str, list[str]] = {
    "Креатин":               ["brain", "muscle", "energy"],
    "Омега-3":               ["brain", "heart"],
    "Витамин D":             ["mood", "bones", "immunity"],
    "B12":                   ["brain", "blood", "energy"],
    "Магний":                ["sleep", "stress", "heart"],
    "Кофеин":                ["energy", "brain", "mood"],
    "L-Теанин":              ["stress", "brain"],
    "Бакопа":                ["brain"],
    "Ежовик":                ["brain"],
    "Гинкго":                ["brain", "heart"],
    "Родиола":               ["energy", "stress", "mood"],
    "Ашваганда":             ["stress", "sleep"],
    "Фосфатидилсерин":       ["brain"],
    "Alpha-GPC":             ["brain"],
    "CDP-холин":             ["brain"],
    "Гуперзин А":            ["brain"],
    "Куркумин":              ["mood", "brain", "joints"],
    "Ресвератрол":           ["metabolism", "heart"],
    "NAC":                   ["brain"],
    "Цинк":                  ["brain", "immunity"],
    "Тирозин":               ["brain", "stress"],
    "Таурин":                ["stress", "sleep"],
    "CoQ10":                 ["energy", "brain", "heart"],
    "Пикногенол":            ["brain"],
    "Готу кола":             ["brain", "stress"],
    "Мелатонин":             ["sleep"],
    "ГАБА":                  ["stress", "sleep"],
    "Глицин":                ["sleep"],
    "Валериана":             ["sleep", "stress"],
    "Бета-аланин":           ["muscle", "energy"],
    "L-цитруллин":           ["heart", "muscle", "energy"],
    "Витамин C":             ["immunity"],
    "Эхинацея":              ["immunity"],
    "Бузина":                ["immunity"],
    "Зверобой":              ["mood"],
    "5-HTP":                 ["mood", "sleep"],
    "Коллаген":              ["skin", "joints"],
    "Пробиотики":            ["gut", "immunity"],
    "B9":                    ["brain", "blood"],
    "Железо":                ["blood", "energy"],
    "Триптофан":             ["sleep", "mood"],
    "Глюкозамин + хондроитин": ["joints"],
    "Витамин E":             ["heart"],
    "Биотин":                ["skin"],
    "L-карнитин":            ["metabolism", "muscle"],
    "BCAA":                  ["muscle"],
    "Аргинин":               ["heart", "muscle"],
    "Кальций":               ["bones"],
    "Гиалуроновая кислота":  ["skin", "joints"],
    "Псиллиум":              ["heart", "gut", "metabolism"],
    "Имбирь":                ["gut"],
    "Чеснок":                ["heart"],
    "Клюква":                ["urinary"],
    "Пустырник":             ["sleep", "stress"],
    "Боярышник":             ["heart"],
    "Бета-глюканы овса":     ["heart", "metabolism"],
    "Рибофлавин":            ["brain"],
    "Лютеин + зеаксантин":   ["vision"],
    "Инозитол":              ["hormones", "stress", "metabolism"],
    "Альфа-липоевая кислота": ["brain", "metabolism"],
    "D-манноза":             ["urinary"],
    "Мака":                  ["hormones"],
    "Хром":                  ["metabolism"],
    "Астаксантин":           ["skin", "vision"],
    "Расторопша":            ["liver"],
    "Лактоферрин":           ["immunity", "blood"],
    "SAMe":                  ["mood"],
    "Йохимбин":              ["metabolism", "hormones"],
    "Пажитник":              ["metabolism", "hormones"],
    "Чёрный тмин":           ["metabolism", "heart"],
    "Трибулус":              ["hormones", "muscle"],
    "NMN":                   ["energy", "brain", "muscle"],
    "Кордицепс":             ["muscle", "energy"],
    "Рейши":                 ["sleep", "immunity"],
    "Хлорофилл":             ["skin"],
    "Сывороточный протеин":  ["muscle"],
    "Глутамин":              ["muscle", "gut", "immunity"],
    "Босвеллия":             ["joints"],
    "Витамин K2":            ["bones", "heart"],
    "Берберин":              ["metabolism"],
    "Кверцетин":             ["immunity"],

    # ---------- v2.0 (13) ----------
    "Шатавари":              ["hormones"],
    "Астрагал":              ["immunity", "heart"],
    "Шлемник":               ["stress", "brain"],
    "Пассифлора":            ["sleep", "stress"],
    "Мелисса":               ["sleep", "stress", "brain"],
    "Лаванда":               ["sleep", "stress"],
    "Чага":                  ["immunity"],
    "Шиитаке":               ["immunity"],
    "Глутатион":             ["liver", "brain"],
    "PQQ":                   ["brain", "energy"],
    "Сульфорафан":           ["liver"],
    "MSM":                   ["joints", "skin"],
    "Гимнема":               ["metabolism", "blood"],

    # ---------- v2.1 (3) ----------
    "B1":                    ["brain"],
    "EPA":                   ["heart", "brain", "mood"],
    "Холин":                 ["brain"],
}