"""Маппинг id карточки → английский поисковый термин для ClinicalTrials.gov.

Используется scripts/fetch_metrics.py. Для каждой карточки — короткий
английский термин (как в query.intr). Проверяется один раз при добавлении,
при 404/пустом ответе скорректировать.
"""

CT_TERMS: dict[str, str] = {
    # ---------- v1.0 (25) ----------
    "Креатин":              "creatine",
    "Омега-3":              "omega-3 OR fish oil OR EPA OR DHA",
    "Витамин D":            "vitamin D OR cholecalciferol",
    "B12":                  "vitamin B12 OR cobalamin",
    "Магний":               "magnesium",
    "Кофеин":               "caffeine",
    "L-Теанин":             "theanine",
    "Бакопа":               "Bacopa",
    "Ежовик":               "Hericium OR lion's mane",
    "Гинкго":               "Ginkgo biloba",
    "Родиола":              "Rhodiola",
    "Ашваганда":            "Withania OR ashwagandha",
    "Фосфатидилсерин":      "phosphatidylserine",
    "Alpha-GPC":            "choline alfoscerate OR alpha-GPC",
    "CDP-холин":            "citicoline",
    "Гуперзин А":           "huperzine A",
    "Куркумин":             "curcumin OR turmeric",
    "Ресвератрол":          "resveratrol",
    "NAC":                  "N-acetylcysteine OR acetylcysteine",
    "Цинк":                 "zinc",
    "Тирозин":              "tyrosine",
    "Таурин":               "taurine",
    "CoQ10":                "coenzyme Q10 OR ubiquinol",
    "Пикногенол":           "pycnogenol",
    "Готу кола":            "Centella asiatica OR gotu kola",

    # ---------- v1.2 (16) ----------
    "Мелатонин":            "melatonin",
    "ГАБА":                 "gamma-aminobutyric acid OR GABA",
    "Глицин":               "glycine",
    "Валериана":            "valerian",
    "Бета-аланин":          "beta-alanine",
    "L-цитруллин":          "citrulline",
    "Витамин C":            "vitamin C OR ascorbic acid",
    "Эхинацея":             "echinacea",
    "Бузина":               "elderberry OR Sambucus",
    "Зверобой":             "St John's wort OR Hypericum",
    "5-HTP":                "5-hydroxytryptophan OR 5-HTP",
    "Коллаген":             "collagen",
    "Пробиотики":           "probiotics",
    "B9":                   "folate OR folic acid",
    "Железо":               "iron supplementation",
    "Триптофан":            "tryptophan",

    # ---------- v2.0 (40) ----------
    "Глюкозамин + хондроитин": "glucosamine OR chondroitin",
    "Витамин E":            "vitamin E OR tocopherol",
    "Биотин":               "biotin",
    "L-карнитин":           "carnitine",
    "BCAA":                 "branched-chain amino acids",
    "Аргинин":              "arginine",
    "Кальций":              "calcium supplementation",
    "Гиалуроновая кислота": "hyaluronic acid",
    "Псиллиум":             "psyllium",
    "Имбирь":               "ginger OR Zingiber",
    "Чеснок":               "garlic OR Allium sativum",
    "Клюква":               "cranberry",
    "Пустырник":            "Leonurus OR motherwort",
    "Боярышник":            "Crataegus OR hawthorn",
    "Бета-глюканы овса":    "beta-glucan",
    "Рибофлавин":           "riboflavin",
    "Лютеин + зеаксантин":  "lutein OR zeaxanthin",
    "Инозитол":             "inositol",
    "Альфа-липоевая кислота": "alpha-lipoic acid",
    "D-манноза":            "D-mannose",
    "Мака":                 "maca OR Lepidium meyenii",
    "Хром":                 "chromium",
    "Астаксантин":          "astaxanthin",
    "Расторопша":           "silymarin OR milk thistle",
    "Лактоферрин":          "lactoferrin",
    "SAMe":                 "S-adenosylmethionine",
    "Йохимбин":             "yohimbine",
    "Пажитник":             "fenugreek OR Trigonella",
    "Чёрный тмин":          "Nigella sativa",
    "Трибулус":             "Tribulus terrestris",
    "NMN":                  "nicotinamide mononucleotide",
    "Кордицепс":            "Cordyceps",
    "Рейши":                "Ganoderma OR reishi",
    "Хлорофилл":            "chlorophyllin OR chlorophyll",
    "Сывороточный протеин": "whey protein",
    "Глутамин":             "glutamine",
    "Босвеллия":            "Boswellia",
    "Витамин K2":           "vitamin K2 OR menaquinone",
    "Берберин":             "berberine",
    "Кверцетин":            "quercetin",
}